name: Trigger PR Review

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    if: contains(github.event.comment.body, '@PR_review')
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Number
        id: extract_pr
        run: echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Extract Repository Info
        id: extract_repo
        run: |
          REPO_FULL_NAME=${{ github.repository }}
          REPO_OWNER=$(echo $REPO_FULL_NAME | cut -d'/' -f1)
          REPO_NAME=$(echo $REPO_FULL_NAME | cut -d'/' -f2)
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Trigger Review in github-pr-reviewer-1.0
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.G_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: "Malintha-101",  // Replace with the correct owner of github-pr-reviewer-1.0
              repo: "github-pr-reviewer-1.0",
              event_type: "trigger-review",
              client_payload: {
                pr_number: process.env.PR_NUMBER,
                repo_owner: process.env.REPO_OWNER,
                repo_name: process.env.REPO_NAME
              }
            });

