name: Trigger PR Review

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    if: contains(github.event.comment.body, '@PR_review')
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Number
        id: extract_pr
        run: |
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Extract Repository Info
        id: extract_repo
        run: |
          REPO_FULL_NAME=${{ github.repository }}
          REPO_OWNER=$(echo $REPO_FULL_NAME | cut -d'/' -f1)
          REPO_NAME=$(echo $REPO_FULL_NAME | cut -d'/' -f2)
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Run curl command with PR_NUMBER, REPO_OWNER, and REPO_NAME
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.G_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{
                 "event_type": "trigger-review",
                 "client_payload": { "pr_number": "${{ env.PR_NUMBER }}", "repo_owner": "${{ env.REPO_OWNER }}", "repo_name": "${{ env.REPO_NAME }}" }
               }' \
               https://api.github.com/repos/Malintha-101/github-pr-reviewer-1.0/dispatches
        shell: /usr/bin/bash -e {0}
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
