name: Trigger PR Review

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    if: contains(github.event.comment.body, '@PR_review')
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Number
        id: extract_pr
        run: |
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Extract Repository Info
        id: extract_repo
        run: |
          REPO_FULL_NAME=${{ github.repository }}
          REPO_OWNER=$(echo $REPO_FULL_NAME | cut -d'/' -f1)
          REPO_NAME=$(echo $REPO_FULL_NAME | cut -d'/' -f2)
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Trigger Review
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = process.env.PR_NUMBER;
            const repoOwner = process.env.REPO_OWNER;
            const repoName = process.env.REPO_NAME;
            await github.repos.createDispatchEvent({
              owner: repoOwner,
              repo: repoName,
              event_type: 'trigger-review',
              client_payload: { pr_number: prNumber, repo_owner: repoOwner, repo_name: repoName }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
