name: Trigger PR Review

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    if: contains(github.event.comment.body, '@PR_review')
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Number
        id: extract_pr
        run: |
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Extract Repository Info
        id: extract_repo
        run: |
          REPO_FULL_NAME=${{ github.repository }}
          REPO_OWNER=$(echo $REPO_FULL_NAME | cut -d'/' -f1)
          REPO_NAME=$(echo $REPO_FULL_NAME | cut -d'/' -f2)
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Trigger Review
        run: |
          gh api repos/Malintha-101/github-pr-reviewer-1.0/dispatches \
            -f event_type=trigger-review \
            -f client_payload.pr_number=${{ env.PR_NUMBER }} \
            -f client_payload.repo_owner=${{ env.REPO_OWNER }} \
            -f client_payload.repo_name=${{ env.REPO_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
