name: Trigger PR Review

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    if: contains(github.event.comment.body, '@PR_review')
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Number
        id: extract_pr
        run: |
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Trigger GitHub PR Reviewer Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.G_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{
                 "event_type": "trigger-review",
                 "client_payload": { "pr_number": "${{ env.PR_NUMBER }}" }
               }' \
               https://api.github.com/repos/Malintha-101/github-pr-reviewer-1.0/dispatches

      - name: Run curl command with PR_NUMBER
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.G_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{
                 "event_type": "trigger-review",
                 "client_payload": { "pr_number": "${{ env.PR_NUMBER }}" }
               }' \
               https://api.github.com/repos/Malintha-101/github-pr-reviewer-1.0/dispatches
        shell: /usr/bin/bash -e {0}
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
